language: python
python:
  - "2.7"
# command to install dependencies
install: "pip install -r requirements.txt && pip install flake8"
# command to run tests
script: flake8 . && python -m unittest -f tests && python setup.py install
